# PostgreSQL Connection
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Supabase SSL REQUIRED
spring.datasource.hikari.data-source-properties.sslmode=require

# Render Port Fix
server.port=${PORT:8080}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# API Key for APILayer
APILAYER_APIKEY=${APILAYER_APIKEY}

# File upload limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Application name
spring.application.name=recruitment-management-system

# JWT Configuration
jwt.secret=mysecretkey123mysecretkey123mysec!!
jwt.expiration=36000000

# enable swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# optional clean URL
springdoc.swagger-ui.path=/swagger-ui.html

# token refresh me saved rahe
springdoc.swagger-ui.persistAuthorization=true

# HikariCP Fix (Render + Supabase)
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.keepalive-time=300000
