# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/recruitment_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${RECRUIT_USERNAME}
spring.datasource.password=${RECRUIT_PASSWORD}



# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# API Key for APILayer
APILAYER_APIKEY=${APILAYER_APIKEY}

# File upload limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Application name
spring.application.name=recruitment-management-system

# JWT Configuration
jwt.secret=mysecretkey123mysecretkey123mysec!!
jwt.expiration=36000000
